const dataTab = [
    {
        id: 1,
        classnames: 'course one-of-four text-2ebd59 MDev',
        imgsrc: 'images/courses/courses-gird-v1-1.png',
        title: 'Iphone App Development Course',
        Overview: 'This iPhone and iPad app development course is designed to get you started in iPhone app development. This course includes Interface Builder, Xcode, Swift, Cocoa Touch programming, and the APIs included in the iOS SDK',
        DESCRIPTION1: 'Training from professional  iPhone application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Advanced iOS Development course',
        plan2:'Swift Basics',
        plan3:'Cocoa Touch Design Patterns  ',
        plan4:'Foundation',
        plan5:'Xcode IDE as a development tool',
        plan6:'View and View Controllers',
        plan7:'Interface builder GUI Tool ',
        plan8:'Table Views ',
        plan9:'Graphics',
        plan10:'Gesture Recognizers        ',
        plan11:'Animation',
        plan12:'System Events',
        plan13:'iPhone and iPad virtual keyboard',
        plan14:'iPad App Development ',
        plan15:'Performance and Debugging',
        plan16:'Manage Navigation ',
        plan17:'Integrate with Apple APIs ',
        plan18:'Integration with 3rd Party APIs',
        plan19:'Concurrency',
        plan20:'Submitting your app for approval',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: 'FREE'
    },
    {
        id: 2,
        classnames: 'course one-of-four text-ea0042 MDev ',
        imgsrc: 'images/courses/courses-gird-v1-2.jpg',  
        title: 'Android Programming Training',
        overview: 'This Android app development course is designed to get you started in Android app development. This course includes different Android development concepts such as Broadcast Receivers, Content Providers, Graphics & Animation, Database for Android App and Integration with APIs. After completing our Android app training course you would be able to build applications for Android.',
        DESCRIPTION1: 'Training from professional Android application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Android App Development',
        plan2:'App Framework',
        plan3:'Hello, World! Android App ',
        plan4:'Android Studio',
        plan5:'Android GUI, Lists and Adapters',
        plan6:'Localisation and Screen Resolution',
        plan7:'Database for Android App ',
        plan8:'Graphics & Animation ',
        plan9:'Broadcast Receivers',
        plan10:'System Services        ',
        plan11:'Integration with APIs',
        plan12:'Publishing your app on the Android Market',     
        Requirements:'You should have industry related and practical experience of Java programming.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 3,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'iPad app development Course',
        overview: 'This iPad app development course is designed to discuss advanced iPad app development. After completing our iPad app training course you would be able to build applications for iPad. ',
        DESCRIPTION1: 'Training from professional iPhone and iPad application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to the iPad course',
        plan2:'Apple’s Built-in View Controllers for iPad',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'NewsStand Kit in iOS 5',
        plan5:'iPad’s unique features',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 4,
        classnames: 'course one-of-four text-256cff MDev',
        imgsrc: 'images/courses/c.png',
        title: 'Introduction to Objective-C Training',
        overview: 'This Objective-C course is designed to get you started in Objective-C development. At the end of the course we will build a practical Objective-C application in the class. ',
        DESCRIPTION1: 'Training from professional Objective-C application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Objective-C Introduction course',
        plan2:'Objective-C Basics',
        plan3:'Programming language core elements ',
        plan4:'Core concepts of Object Oriented Programming',
        plan5:'Objective-C Classes',
        plan6:'Custom Classes',
        plan7:'Objective-C Synthetized Getter/Setter Functions ',
        plan8:'Objective-C Class Objects & Polymorphism ',
        plan9:'Objective-C Exceptions',
        plan10:'Objective-C Categories & Protocols        ',
        plan11:'Cocoa Basics',
        plan12:'Cocoa Strings',
        plan13:'Cocoa Containers & Collections',
        plan14:'Cocoa File Management',
        plan15:'Cocoa Memory Management',
        plan16:'Cocoa Archiving',
        plan17:'Debugging and testing',        
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$89.00'
    },
    {
        id: 5,
        classnames: 'course one-of-four text-8828ff MDev',
        imgsrc: 'images/courses/swift.jpg',
        title: 'Swift Course',
        overview: 'This Swift course is designed to get you started in Swift development. At the end of the course we will build a practical Swift application in the class. This app development project will ensure that you can build your own Swift applications. ',
        DESCRIPTION1: 'Training from professional Swift application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Swift iOS Development Course',
        plan2:'Swift Basics',
        plan3:'Swift Design patterns ',
        plan4:'Swift Foundation',
        plan5:'Swift Introduction course',
        plan6:'Swift Basics',
        plan7:'Programming language core elements ',
        plan8:'Core concepts of Object Oriented Programming ',
        plan9:'Swift Classes',
        plan10:'Custom Classes        ',
        plan11:'Swift Synthetized Getter/Setter Functions',
        plan12:'Swift Class Objects & Polymorphism',
        plan13:'Swift Exceptions',
        plan14:'Swift Categories & Protocols',
        plan15:'Cocoa Basics',
        plan16:'Cocoa Strings',
        plan17:'Cocoa Containers & Collections',   
        plan18:'Cocoa File Management',
        plan19:'Cocoa Memory Management',
        plan20:'Cocoa Archiving',
        plan21:'Debugging and testing',
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 6,
        classnames: 'course one-of-four text-0dacff MDev',
        imgsrc: 'images/courses/courses-gird-v1-6.jpg',
        title: 'Advanced Android App Development Training',
        overview: 'This Android app development course is designed to get you started in Android app development. This course includes different Android development concepts such as Broadcast Receivers, Content Providers, Graphics & Animation, Database for Android App and Integration with APIs. After completing our Android app training course you would be able to build applications for Android. ',
        DESCRIPTION1: 'Training from professional Android application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Android App development IDE',
        plan2:'Testing Android Apps',
        plan3:'Frameworks ',
        plan4:'Deep Link in Android',
        plan5:'Centralised Database for Android App',
        plan6:'Android GUI, Lists, Adapters and Customisation',
        plan7:'Multimedia',
        plan8:'Content Providers',
        plan9:'Centralised Database for Android App',
        plan10:'Integrate with Core Services and other Android Apps',
        plan11:'Publishing your app on the Android Market',
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 7,
        classnames: 'course one-of-four text-536dfe MDev',
        imgsrc: 'images/courses/courses-gird-v1-7.jpg',
        title: 'Xamarin Training',
        overview: 'Xamarin allows you to build native mobiles apps for mobile platforms such as iPhone, Android, Windows Phone and Blackberry using C#, Visual Studio and .NET. Some of the features that Xamarin supports are camera, compass, contacts, files, geolocation and media etc. ',
        overview: 'Xamarin supports the following platforms:',
        overview: 'Apple iOS',
        overview: 'Google Android',
        overview: 'Microsoft Windows Phone',
        DESCRIPTION1: 'Training from professional Xamarin application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to Xamarin platform',
        plan2:'Cross-Platform App Development',
        plan3:'Navigation ',
        plan4:'Data in Mobile',
        plan5:'Xamarin Web Services',
        plan6:'Xamarin.Forms',
        plan7:'Enterprise Services',
        plan8:'Android App Development in Xamarin',
        plan9:'Testing',
        plan10:'Publishing an application',
        Requirements: 'A good knowledge of C#, Visual Studio and .NET is required.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 8,
        classnames: 'course one-of-four text-ffbf13 MDev',
        imgsrc: 'images/courses/courses-gird-v1-8.jpg',
        title: 'PhoneGap Training',
        count: '5.0 (980)',
        price: '$89.00'
    },
    {
        id: 9,
        classnames: 'course one-of-four text-2ebd59 MDev NET',
        imgsrc: 'images/background1.png',
        title: 'Xamarin Course',
        count: '5.0 (980)',
        price: 'FREE'
    },
    {
        id: 10,
        classnames: 'course one-of-four text-ff562f MDev',
        imgsrc: 'images/background2.png',
        title: 'GAME DEVELOPMENT TRAINING',
        Overview: 'You’ll learn how to seamlessly create games for a variety of platforms and game engines including Unreal Engine, Blender, Unity and more. Learn the tricks of the trade in game animation and how to make your motion graphics come alive.',
        DESCRIPTION1: 'Training from professional Programmers',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Getting Started',
        plan2:'The Level Editor',
        plan3:'Actros in Unreal',
        plan4:'Working with Blueprints',
        plan5:'Collisions',
        plan6:'User Interface',
        Requirements:'There are no prerequisites for attending this course.',
         count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 11,
        classnames: 'course one-of-four text-0dacff MDev',
        imgsrc: 'images/background3.png',
        title: 'Introduction to Programming Course',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 12,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/background4.png',
        title: 'Game Development Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 13,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'C# Training',
        Overview : 'This C# course explains how to use C# to create applications. After completing this training course you would be able to use C# on your projects. Few practical C# based projects at the end of the course will ensure that you can apply C# on your projects.',
        DESCRIPTION1: 'Training from professional C# developers',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Overview of the Microsoft .NET Platform',
        plan2:'Overview of C#',
        plan3:'Using Value-Type Variables ',
        plan4:'Statements and Exceptions',
        plan5:'Methods and Parameters',
        plan6:'Arrays',
        plan7:'Version Control ',
        plan8:'Essentials of Object-Oriented Programming ',
        plan9:'Using Reference-Type Variables',
        plan10:'Creating and Destroying Object',
        plan11:'Inheritance in C#',
        plan12:'Aggregation, Namespaces, and Advanced Scope',
        plan13:'Operators, Delegates, and Events',
        plan14:'Properties and Indexers',
        plan15:'Attributes',
        
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 14,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'C++ Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 15,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'VB.NET Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 16,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Windows Forms using C# Course',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 17,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'WPF using C# Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 18,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Java SE7 Fundamentals Course',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 19,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'OCA Java SE 8 Programmer Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 20,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'OCP Java SE 8 Programmer Course',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 21,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Java SE7 Programming Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 22,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Python for beginners Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 23,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 24,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Advanced Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 26,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Science using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 27,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Analysis using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 28,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Machine Learning using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 29,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Deep Learning using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 30,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Django Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 31,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Science using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 32,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Analysis using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 33,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Machine Learning using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 34,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Deep Learning using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 35,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'MTA Software Development Fundamentals with .NET Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 36,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'ASP.NET Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 37,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'ASP.NET MVC Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
                                        

    
    
]


export default dataTab;
