const dataTab = [
    {
        id: 1,
        classnames: 'course one-of-four text-2ebd59 MDev',
        imgsrc: 'images/courses/courses-gird-v1-1.png',
        title: 'Iphone App Development Course',
        Overview: 'This iPhone and iPad app development course is designed to get you started in iPhone app development. This course includes Interface Builder, Xcode, Swift, Cocoa Touch programming, and the APIs included in the iOS SDK',
        DESCRIPTION1: 'Training from professional  iPhone application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Advanced iOS Development course',
        plan2:'Swift Basics',
        plan3:'Cocoa Touch Design Patterns  ',
        plan4:'Foundation',
        plan5:'Xcode IDE as a development tool',
        plan6:'View and View Controllers',
        plan7:'Interface builder GUI Tool ',
        plan8:'Table Views ',
        plan9:'Graphics',
        plan10:'Gesture Recognizers        ',
        plan11:'Animation',
        plan12:'System Events',
        plan13:'iPhone and iPad virtual keyboard',
        plan14:'iPad App Development ',
        plan15:'Performance and Debugging',
        plan16:'Manage Navigation ',
        plan17:'Integrate with Apple APIs ',
        plan18:'Integration with 3rd Party APIs',
        plan19:'Concurrency',
        plan20:'Submitting your app for approval',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: 'FREE'
    },
    {
        id: 2,
        classnames: 'course one-of-four text-ea0042 MDev ',
        imgsrc: 'images/courses/courses-gird-v1-2.jpg',  
        title: 'Android Programming Training',
        overview: 'This Android app development course is designed to get you started in Android app development. This course includes different Android development concepts such as Broadcast Receivers, Content Providers, Graphics & Animation, Database for Android App and Integration with APIs. After completing our Android app training course you would be able to build applications for Android.',
        DESCRIPTION1: 'Training from professional Android application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Android App Development',
        plan2:'App Framework',
        plan3:'Hello, World! Android App ',
        plan4:'Android Studio',
        plan5:'Android GUI, Lists and Adapters',
        plan6:'Localisation and Screen Resolution',
        plan7:'Database for Android App ',
        plan8:'Graphics & Animation ',
        plan9:'Broadcast Receivers',
        plan10:'System Services        ',
        plan11:'Integration with APIs',
        plan12:'Publishing your app on the Android Market',     
        Requirements:'You should have industry related and practical experience of Java programming.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 3,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'iPad app development Course',
        overview: 'This iPad app development course is designed to discuss advanced iPad app development. After completing our iPad app training course you would be able to build applications for iPad. ',
        DESCRIPTION1: 'Training from professional iPhone and iPad application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to the iPad course',
        plan2:'Apple’s Built-in View Controllers for iPad',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'NewsStand Kit in iOS 5',
        plan5:'iPad’s unique features',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 4,
        classnames: 'course one-of-four text-256cff MDev',
        imgsrc: 'images/courses/c.png',
        title: 'Introduction to Objective-C Training',
        overview: 'This Objective-C course is designed to get you started in Objective-C development. At the end of the course we will build a practical Objective-C application in the class. ',
        DESCRIPTION1: 'Training from professional Objective-C application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Objective-C Introduction course',
        plan2:'Objective-C Basics',
        plan3:'Programming language core elements ',
        plan4:'Core concepts of Object Oriented Programming',
        plan5:'Objective-C Classes',
        plan6:'Custom Classes',
        plan7:'Objective-C Synthetized Getter/Setter Functions ',
        plan8:'Objective-C Class Objects & Polymorphism ',
        plan9:'Objective-C Exceptions',
        plan10:'Objective-C Categories & Protocols        ',
        plan11:'Cocoa Basics',
        plan12:'Cocoa Strings',
        plan13:'Cocoa Containers & Collections',
        plan14:'Cocoa File Management',
        plan15:'Cocoa Memory Management',
        plan16:'Cocoa Archiving',
        plan17:'Debugging and testing',        
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$89.00'
    },
    {
        id: 5,
        classnames: 'course one-of-four text-8828ff MDev',
        imgsrc: 'images/courses/swift.jpg',
        title: 'Swift Course',
        overview: 'This Swift course is designed to get you started in Swift development. At the end of the course we will build a practical Swift application in the class. This app development project will ensure that you can build your own Swift applications. ',
        DESCRIPTION1: 'Training from professional Swift application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction Swift iOS Development Course',
        plan2:'Swift Basics',
        plan3:'Swift Design patterns ',
        plan4:'Swift Foundation',
        plan5:'Swift Introduction course',
        plan6:'Swift Basics',
        plan7:'Programming language core elements ',
        plan8:'Core concepts of Object Oriented Programming ',
        plan9:'Swift Classes',
        plan10:'Custom Classes        ',
        plan11:'Swift Synthetized Getter/Setter Functions',
        plan12:'Swift Class Objects & Polymorphism',
        plan13:'Swift Exceptions',
        plan14:'Swift Categories & Protocols',
        plan15:'Cocoa Basics',
        plan16:'Cocoa Strings',
        plan17:'Cocoa Containers & Collections',   
        plan18:'Cocoa File Management',
        plan19:'Cocoa Memory Management',
        plan20:'Cocoa Archiving',
        plan21:'Debugging and testing',
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 6,
        classnames: 'course one-of-four text-0dacff MDev',
        imgsrc: 'images/courses/courses-gird-v1-6.jpg',
        title: 'Advanced Android App Development Training',
        overview: 'This Android app development course is designed to get you started in Android app development. This course includes different Android development concepts such as Broadcast Receivers, Content Providers, Graphics & Animation, Database for Android App and Integration with APIs. After completing our Android app training course you would be able to build applications for Android. ',
        DESCRIPTION1: 'Training from professional Android application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Android App development IDE',
        plan2:'Testing Android Apps',
        plan3:'Frameworks ',
        plan4:'Deep Link in Android',
        plan5:'Centralised Database for Android App',
        plan6:'Android GUI, Lists, Adapters and Customisation',
        plan7:'Multimedia',
        plan8:'Content Providers',
        plan9:'Centralised Database for Android App',
        plan10:'Integrate with Core Services and other Android Apps',
        plan11:'Publishing your app on the Android Market',
        Requirements:'You should have good experience with OOP (object-oriented programming), Inheritance, Aggregation, Namespaces and Advanced Scope etc.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 7,
        classnames: 'course one-of-four text-536dfe MDev',
        imgsrc: 'images/courses/courses-gird-v1-7.jpg',
        title: 'Xamarin Training',
        overview: 'Xamarin allows you to build native mobiles apps for mobile platforms such as iPhone, Android, Windows Phone and Blackberry using C#, Visual Studio and .NET. Some of the features that Xamarin supports are camera, compass, contacts, files, geolocation and media etc. ',
        DESCRIPTION1: 'Training from professional Xamarin application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to Xamarin platform',
        plan2:'Cross-Platform App Development',
        plan3:'Navigation ',
        plan4:'Data in Mobile',
        plan5:'Xamarin Web Services',
        plan6:'Xamarin.Forms',
        plan7:'Enterprise Services',
        plan8:'Android App Development in Xamarin',
        plan9:'Testing',
        plan10:'Publishing an application',
        Requirements: 'A good knowledge of C#, Visual Studio and .NET is required.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 8,
        classnames: 'course one-of-four text-ffbf13 MDev',
        imgsrc: 'images/courses/courses-gird-v1-8.jpg',
        title: ' Ionic Training',
        overview: 'Ionic allows you to build native mobiles apps for mobile platforms such as iPhone and Android using web standards like HTML5, CSS3 and JavaScript. Some of the features that Ionic supports are camera, compass, contacts, files, geolocation and media etc. ',
        DESCRIPTION1: 'Training from professional Ionic application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Development Environment for Ionic',
        plan2:'Mobile UIs',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'Apache Ionic and Ionic build',
        plan5:'Ionic APIs',
        plan6:'Workflow',
        plan7:'Debug',
        Requirements:'A good knowledge of HTML5 and CSS3 is required. We provide HTML5 training and CSS3 courses. It is necessary to have to have some knowledge of jQuery for mobile, JavaScript and jQuery.',
        count: '5.0 (980)',
        price: '$89.00'
    },
    {
        id: 9,
        classnames: 'course one-of-four text-2ebd59 MDev NET',
        imgsrc: 'images/background1.png',
        title: ' INTRODUCTION TO PROGRAMMING COURSE',
        overview: 'This Programming course explains how to use computer Programming languages and the primary concepts behind different programming languages. After completing this training course you would be able to take programming courses in other computer languages. ',
        DESCRIPTION1: 'Training from professional Programmers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to programming',
        plan2:'Planning and designing Programs',
        plan3:'Variables, data types and validation ',
        plan4:'Control flow structures',
        plan5:'Functions, Methods and Parameters',
        plan6:'Best practices and pitfalls',
        plan7:'Procedural vs Object-Oriented Programming',
        plan8:'Debugging',
        Requirements:'You should be able to use computer and internet. You should be able to create and copy folders and files on your computer. Typing skills are beneficial.',
        count: '5.0 (980)',
        price: 'FREE'
    },
    {
        id: 10,
        classnames: 'course one-of-four text-ff562f MDev',
        imgsrc: 'images/background2.png',
        title: 'GAME DEVELOPMENT TRAINING',
        Overview: 'You’ll learn how to seamlessly create games for a variety of platforms and game engines including Unreal Engine, Blender, Unity and more. Learn the tricks of the trade in game animation and how to make your motion graphics come alive.',
        DESCRIPTION1: 'Training from professional Programmers',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Getting Started',
        plan2:'The Level Editor',
        plan3:'Actros in Unreal',
        plan4:'Working with Blueprints',
        plan5:'Collisions',
        plan6:'User Interface',
        Requirements:'There are no prerequisites for attending this course.',
         count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 11,
        classnames: 'course one-of-four text-0dacff MDev',
        imgsrc: 'images/background3.png',
        title: 'C Course',
        overview: 'This C course explains how to use C to create applications. After completing this training course you would be able to use C on your projects. Few practical C based projects at the end of the course will ensure that you can apply C on your projects. ',
        DESCRIPTION1:'Training from professional C developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'The basics of C programming',
        plan2:'"Advanced" techniques of the C language',
        plan3:'Data structures',
        Requirements:'It is not necessary to have knowledge of any programming language before you start this C course but If you have some knowledge of programming then it will make learning this course even easier. ',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 12,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/background4.png',
        title: 'C++ Training',
        overview: 'This C++ course explains how to use C++ to create applications. After completing this training course you would be able to use C++ on your projects. Few practical C++ based projects at the end of the course will ensure that you can apply C++ on your projects. ',
        DESCRIPTION1:'Training from professional C++ developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'C++ Overview',
        plan2:'Functions and Variables',
        plan3:'Object Oriented Programming',
        plan4:'ADO .NET Database Programming',
        plan5:'Multithreading',
        plan6:'Windows Forms Application in C++',
        plan7:'Advanced C++',
        Requirements:'It is not necessary to have knowledge of any programming language before you start this C++ course but If you have some knowledge of programming then it will make learning this course even easier ',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 13,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'C# Training',
        Overview : 'This C# course explains how to use C# to create applications. After completing this training course you would be able to use C# on your projects. Few practical C# based projects at the end of the course will ensure that you can apply C# on your projects.',
        DESCRIPTION1: 'Training from professional C# developers',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Overview of the Microsoft .NET Platform',
        plan2:'Overview of C#',
        plan3:'Using Value-Type Variables ',
        plan4:'Statements and Exceptions',
        plan5:'Methods and Parameters',
        plan6:'Arrays',
        plan7:'Version Control ',
        plan8:'Essentials of Object-Oriented Programming ',
        plan9:'Using Reference-Type Variables',
        plan10:'Creating and Destroying Object',
        plan11:'Inheritance in C#',
        plan12:'Aggregation, Namespaces, and Advanced Scope',
        plan13:'Operators, Delegates, and Events',
        plan14:'Properties and Indexers',
        plan15:'Attributes',
        
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 14,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'VB.Net Training',
        overview: 'This VB.NET course explains how to use VB.NET to create applications. After completing this training course you would be able to use VB.NET on your projects. This instructor-led course provides students with the knowledge and skills needed to develop applications in Microsoft Visual Basic .NET for the Microsoft .NET platform. The course focuses on user interfaces, program structure, language syntax, and implementation details. ',
        DESCRIPTION1: 'Training from professional VB.NET developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Getting Started',
        plan2:'Working with Forms and Controls',
        plan3:'Using Variables and Arrays ',
        plan4:'Working with Procedures ',
        plan5:'Decision Structures and Loops',
        plan6:'Validating User Input',
        plan7:'Object-Oriented Programming in Visual Basic .NET',
        plan8:'Handling Errors and Exceptions',
        plan9:'Enhancing the User Interface',
        plan10:'Web Forms and XML Web Services',
        plan11:'Using ADO.NET',
        plan12:'Deploying Applications',
        Requirements:'You must have prior project based experience in any programming languages like JavaScript, PHP, C#, Python, Java etc.',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 15,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Windows Forms using C# Course',
        overview: 'This Windows Forms using C# course explains how to build Windows Forms apps. After completing this training course you would be able to create Windows Forms applications using C#. ',
        DESCRIPTION1: 'Training from professional Windows Forms developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'How does this course work',
        plan2:'Learning the fundamentals',
        plan3:'Controlling program flow ',
        plan4:'Operators ',
        plan5:'Methods and arrays',
        plan6:'Creating, Saving, reading, previewing and printing files',
        plan7:'Database project',
        plan8:'Miscellaneous',
        plan9:'Search all columns of data grid view project',
        plan10:'Using nullable data types with databases',       
        Requirements:'Some prior knowledge of programming concepts in any programming language will be helpful.',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 16,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'WPF using C# Training',
        overview: 'This Windows Presentation Foundation (WPF) using WPF using C# course explains how to use WPF using C# to create applications. After completing this training course you would be able to use WPF using C# on your projects. Few practical WPF using C# based projects at the end of the course will ensure that you can apply WPF using C# on your projects.  ',
        DESCRIPTION1: 'Training from professional WPF developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to WPF',
        plan2:'XAML',
        plan3:'WPF Controls ',
        plan4:'Layout ',
        plan5:'Dialogs',
        plan6:'Menus and Commands',
        plan7:'Toolbars and Status Bars',
        plan8:'Dependency Properties and Routed Events',
        plan9:'Resources',
        plan10:'Data Binding',  
        plan11:'Styles, Templates, Skins and Themes ',
        plan12:'Windows Forms and WPF Interoperation',
        Requirements:'Prior practical and project based experience of C# is required.',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 17,
        classnames: 'course one-of-four text-ff562f SDev NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Java SE7 Fundamentals Course',
        overview: 'The Java SE 7 Fundamentals course was designed to enable students with little or no programming experience to begin to learn programming using the Java programming language. The course teaches the significance of object-oriented programming, the keywords and constructs of the Java programming language, and the steps required to create simple Java technology programs. ',
        DESCRIPTION1: 'Training from professional JAVA developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Identify the key concepts of the Java programming language',
        plan2:'Identify the Java technology groups',
        plan3:'Recognize how IDEs help speed development time ',
        plan4:'Sequence the stages in the product life cycle ',
        plan5:'Identify the features of objects, attributes, and operations',
        plan6:'Recognize factors to consider when designing and modeling a class',
        plan7:'Identify how to define a class using Java',
        plan8:'Recognize how to test and execute a simple Java program',
        plan9:'Use the features of the IDE debugger',
        plan10:'Create a project in the NetBeans IDE',  
        plan11:'Recognize how to use NetBeans to create and compile a Java class and to create a test program  ',
        plan12:'Recognize the features of the NetBeans debugger',
        Requirements:'Prior practical and project based experience of C# is required.',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 18,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'OCA Java SE 8 Programmer Training',
        overview: 'The course teaches the significance of object-oriented programming, the keywords and constructs of the Java programming language, and the steps required to create simple Java technology programs. ',
        DESCRIPTION1: 'Use Java programming language constructs to create a Java technology application. ',
        DESCRIPTION2:'Use decision and looping constructs and methods to dictate program flow. ',
        DESCRIPTION3:'Understand basic object oriented concepts such as inheritance, encapsulation, and abstraction.',
        DESCRIPTION4:'Use and manipulate object references, and to write simple error handling code.',
        DESCRIPTION5:'Use the new SE 8 java.time and java.time.format packages to format and print the local date and time.',
        DESCRIPTION6:'Specify a data modification by passing a predicate lambda expression to the Collections class.',
        plan1:'What Is a Java Program?',
        plan2:'Creating a Java Main Class',
        plan3:'Data In the Cart ',
        plan4:'Managing Multiple Items ',
        plan5:'Describing Objects and Classes',
        plan6:'Manipulating and Formatting the Data in Your Program',
        plan7:'Creating and Using Methods',
        plan8:'Using Encapsulation',
        plan9:'More on Conditionals',
        plan10:'More on Arrays and Loops',  
        plan11:'Using Inheritance  ',
        plan12:'Using Interfaces',
        plan13:'Handling Exceptions',
        Requirements:'Prior practical and project based experience of C# is required.',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 19,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'OCP Java SE 8 Programmer Course',
        overview: 'The course teaches the significance of object-oriented programming, the keywords and constructs of the Java programming language, and the steps required to create simple Java technology programs.  ',
        DESCRIPTION1: 'Use Java programming language constructs to create a Java technology application. ',
        DESCRIPTION2:'Use decision and looping constructs and methods to dictate program flow. ',
        DESCRIPTION3:'Understand basic object oriented concepts such as inheritance, encapsulation, and abstraction.',
        DESCRIPTION4:'Use and manipulate object references, and to write simple error handling code.',
        DESCRIPTION5:'Use the new SE 8 java.time and java.time.format packages to format and print the local date and time.',
        DESCRIPTION6:'Specify a data modification by passing a predicate lambda expression to the Collections class.',
        plan1:'Java Platform Overview',
        plan2:'Java Syntax and Class Review',
        plan3:'Encapsulation and Subclassing ',
        plan4:'Overriding Methods, Polymorphism, and Static Classes ',
        plan5:'Abstract and Nested Classes',
        plan6:'Interfaces and Lambda Expressions',
        plan7:'Collections and Generics',
        plan8:'Collections Streams, and Filters',
        plan9:'Lambda Built-in Functional Interfaces',
        plan10:'Lambda Operations',  
        plan11:'Exceptions and Assertions ',
        plan12:'Java Date/Time AP',
        plan13:'I/O Fundamentals',
        plan14:'File I/O (NIO.2)',
        plan15:'Concurrency',
        plan16:'The Fork-Join Framework',
        plan17:'Parallel Streams',
        plan18:'Database Applications with JDBC ',
        plan19:'Localization',
        Requirements:'Prior practical and project based experience of C# is required. ',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 20,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'JAVA SE7 Programming Training',
        overview: 'This course covers the core Application Programming Interfaces (API) you will use to design object-oriented applications with Java. Learn to create classes that subclass other classes, extend abstract classes, and program with interfaces.  ',
        DESCRIPTION1: 'Create Java technology applications with the latest JDK 7 Technology and the NetBeans Integrated Development Environment (IDE).  ',
        DESCRIPTION2:'Enhance object-oriented thinking skills using design patterns and best practices. ',
        DESCRIPTION3:'Understand basic object oriented concepts such as inheritance, encapsulation, and abstraction.',
        DESCRIPTION4:'Identify good practices in the use of the language to create robust Java applications.',
        DESCRIPTION5:'Manipulate files, directories and file systems.',
        DESCRIPTION6:'Write database applications using standard SQL queries through JDBC.',
        DESCRIPTION7:'Create high-performance multi-threaded applications.',
        plan1:'Working with GUIs ',
        plan2:'Java Platform Overview',
        plan3:'Java Syntax and Class Review ',
        plan4:'Java Class Design ',
        plan5:'Advanced Class Design',
        plan6:'Inheritance with Java Interfaces',
        plan7:'Generics and Collections',
        plan8:'String processing',
        plan9:'Exceptions and Assertions',
        plan10:'I/O Fundamentals',  
        plan11:'File I/O with NIO 2 ',
        plan12:'Concurrency',
        plan13:'Database Application with JDBC',
        plan14:'Localization',
        Requirements:'Experience with at least one programming language, Understand object-oriented principles, Basic understanding of database concepts and SQL syntax. ',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 21,
        classnames: 'course one-of-four text-ff562f SDev',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Python for beginners Training',
        overview: 'This Python training is designed for Python beginners. This course is for you if you are interested in creating Python applications for yourself or for others.  ',
        DESCRIPTION1: 'Training from professional Python developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'What is Python',
        plan2:'Where is Python used',
        plan3:'Python community ',
        plan4:'Where to get Python help ',
        plan5:'What languages are similar to Python',
        plan6:'Python Interpreter',
        plan7:'Python environment',
        plan8:'Arrays',
        plan9:'Defining Functions',
        plan10:'Default Argument Values',  
        plan11:'Argument Passing ',
        plan12:'Conditions',
        plan13:'What are Loops and when to use them',
        plan14:'For Loop',
        plan15:'While Loop',
        plan16:'Conditional IF statements',
        plan17:'IF with Else statements',
        plan18:'Operators ',
        plan19:'Strings',
        plan19:'Structured programming vs Object Oriented Programming',
        plan19:'Object-Oriented terminology',
        plan19:'Basic concept of Class, Object and Inheritance in Python',
        Requirements:'It is not necessary to have knowledge of Python before you start this Python course but you must have some knowledge of basic programming concepts like variable, loops, functions. ',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 22,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'PYTHON COURSE',
        overview: 'This Python training is designed for Python beginners. This course is for you if you are interested in creating Python applications for yourself or for others.  ',
        DESCRIPTION1: 'Training from professional Python developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Python 3: The Basics',
        plan2:'Python Set-up',
        plan3:'Python 3 Features ',
        plan4:'Common elements of Python Programming ',
        plan5:'Conditional Statements in Python',
        plan6:'Loops',
        plan7:'Python 3 String Management',
        plan8:'Python Functions',
        plan9:'Collections',
        plan10:'Advanced Collections',  
        plan11:'Regular Expressions ',
        plan12:'File Handling',
        plan13:'Database with Python',
        plan14:'Modules and Packages',
        plan15:'Classes and OOP',
        plan16:'Error Handling and Exceptions',
        Requirements:'It is not necessary to have knowledge of Python before you start this Python course but you must have some practical experience of any other programming language for. ',
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 23,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Advanced Python Training',      
        overview: 'This advanced Python course explains how to use advanced Python to create applications. This course is not suitable for beginners in Python. ',
        DESCRIPTION1: 'Training from professional Python developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'ADVANCED OBJECT ORIENTATION',
        plan2:'MODERN APPROACHES TO EXCEPTION HANDLING',
        plan3:'ADVANCED LANGUAGE TECHNIQUES ',
        plan4:'FUNCTIONAL PROGRAMMING ',
        plan5:'WORKING WITH EXCEL',
        plan6:'WORKING WITH DATABASES',
        plan7:'Advanced Python',        
        Requirements:'Before starting this advanced course, you should have worked with variable, loops, functions, object oriented programming, class and inheritance etc in Python. ',             
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 24,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: ' Data Science using Python course',
        overview: 'This Python Data Science course explains how to use Python for Data Science. After completing this training course you would be able to use Python on your Data Science projects.  ',
        DESCRIPTION1: 'Training from professional Python Data Science developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction',
        plan2:'Statistical Computing with Python',
        plan3:'Visualisation and plotting ',
        plan4:'Linear Algebra ',
        plan5:'Statistics',
        plan6:'Probability',
        plan7:'Hypothesis',
        plan8:'Regression',
        plan9:'Project',        
        Requirements:'It is not necessary to have knowledge of Data Analysis before you start this course but you must have some practical experience of Python programming language and statistics. ',  
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 26,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: ' Data Analysis using Python Training',
        overview: 'This Data Analysis using Python course explains how to use Python to analyse data. After completing this training course you would be able to use Python on your Data Analysis projects.   ',
        DESCRIPTION1: 'Training from professional Anaconda and Jupyter NotebookData Analysis using Python developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction',
        plan2:'Anaconda and Jupyter Notebook',
        plan3:'NumPy ',
        plan4:'Pandas ',
        plan5:'Visualisation and plotting',
        plan6:'Project',               
        Requirements:'It is not necessary to have knowledge of Data Analysis before you start this course but you must have some practical experience of Python programming language. ', 
        count: '5.0 (980)',
        price: '$49.00'
    },{
        id: 27,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Machine Learning using Python Course',
        overview: 'This Machine Learning course explains how to use Python for Machine Learning . After completing this training course you would be able to use Machine Learning on your projects.   ',
        DESCRIPTION1: 'Training from professional Python Machine Learning developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'ML',
        plan2:'NLP and NLTK',
        plan3:'Project ',              
        Requirements:'It is not necessary to have knowledge of Machine Learning before you start this course but you must have some practical experience of Python programming language.  ', 
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 28,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: ' Deep Learning using Python Training',
        overview: 'This Deep Learning course explains how to use Python for DL (Deep Learning). After completing this training course you would be able to use Deep Learning on your projects.   ',
        DESCRIPTION1: 'Training from professional  Python Deep Learning developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Need for deep learning ',
        plan2:'Introduction to Tensorflow',
        plan3:'Tensorflow :Eager execution and hello world ',  
        plan3:'Tensorflow:Modelling an equation in Tensorflow ',
        plan3:'calculating loss and gradient ',
        plan3:'Hands On: Regression using tensorflow(Eager Execution and Eager Normalization)',
        plan3:'Gradient',
        plan3:'Keras framework',
        plan3:'Classification using MNIST',
        Requirements:'It is not necessary to have knowledge of Deep Learning before you start this course but you must have some practical experience of Python programming language.  ', 
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 29,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: ' Django Course',
        overview: 'This Django course explains how to use Django framework to create dynamic web applications. After completing this training course you would be able to use Django on your website projects.   ',
        DESCRIPTION1: 'Training from professional Django web developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction ',
        plan2:'Models in Django',
        plan3:'Views in Django',  
        plan3:'Template ',
        plan3:'Tools',
        plan3:'Testing',
        plan3:'Forms',
        plan3:'Security',
        plan3:'Project',
        Requirements:'Project based experience of HTML, CSS, JavaScript, SQL and Python is required. ', 
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 30,
        classnames: 'course one-of-four text-ff562f Pyt',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Django Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 31,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Science using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 32,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Data Analysis using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 33,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Machine Learning using Python Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 34,
        classnames: 'course one-of-four text-ff562f DSA',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'Deep Learning using Python Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 35,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'MTA Software Development Fundamentals with .NET Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 36,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'ASP.NET Course',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 37,
        classnames: 'course one-of-four text-ff562f NET',
        imgsrc: 'images/courses/courses-gird-v1-10.jpg',
        title: 'ASP.NET MVC Training',
        count: '5.0 (980)',
        price: '$49.00'
    },
                                        

    
    
]


export default dataTab;
