const dataTab = [
    {
        id: 1,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'iPad app development Course',
        overview: 'This iPad app development course is designed to discuss advanced iPad app development. After completing our iPad app training course you would be able to build applications for iPad. ',
        DESCRIPTION1: 'Training from professional iPhone and iPad application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to the iPad course',
        plan2:'Apple’s Built-in View Controllers for iPad',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'NewsStand Kit in iOS 5',
        plan5:'iPad’s unique features',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 2,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'iPad app development Course',
        overview: 'This iPad app development course is designed to discuss advanced iPad app development. After completing our iPad app training course you would be able to build applications for iPad. ',
        DESCRIPTION1: 'Training from professional iPhone and iPad application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to the iPad course',
        plan2:'Apple’s Built-in View Controllers for iPad',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'NewsStand Kit in iOS 5',
        plan5:'iPad’s unique features',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 3,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'iPad app development Course',
        overview: 'This iPad app development course is designed to discuss advanced iPad app development. After completing our iPad app training course you would be able to build applications for iPad. ',
        DESCRIPTION1: 'Training from professional iPhone and iPad application developers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to the iPad course',
        plan2:'Apple’s Built-in View Controllers for iPad',
        plan3:'Designing your own View Controllers for iPad ',
        plan4:'NewsStand Kit in iOS 5',
        plan5:'iPad’s unique features',
        Requirements:'You should have some experience with iPhone App development.',
        count: '5.0 (980)',
        price: '$24.00'
    },
]

export default dataTab;