const dataTab = [
    {
        id: 1,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'MongoDB',
        overview: 'This mongoDB course is designed to provide delegates with the necessary knowledge to start using MongoDB on projects.',
        DESCRIPTION1: 'Training from professional certified trainers ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction to NoSQL Architecture with MongoDB',
        plan2:'CRUD and the MongoDB Shell',
        plan3:'Data Modelling and Schema Design ',
        plan4:'Querying Data',
        plan5:'Manipulating Data',
        plan6:'High Performance Options',
        plan7:'Aggregation Framework',
        plan8: 'Indexing',
        plan9: 'Replication',
        plan10: 'Administration',
        plan11: 'Using an API',
        Requirements:'Basic knowledge of database and SQL would be required.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 2,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'Big Data Analytics Training',
        overview: 'This Big Data Analytics course explains how to use Big Data Analytics language to create and manage databases. After completing this training course you would be able to use Big Data Analytics on your small database projects. ',
        DESCRIPTION1: 'Training from professional Big Data Analytics developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'What is Data Analytics',
        plan2:'The Data Ecosystem',
        plan3:'Gathering and Wrangling Data ',
        plan4:'Mining & Visualizing Data and Communicating Results',
        plan5:'Career Opportunities and Data Analysis in Action',
        Requirements:'This Big Data Analytics training is designed for Big Data Analytics beginners. This course is for you if you are interested in learning Big Data Analytics Language practically.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 3,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'Big Data Training',
        overview: 'This Big Data Analytics course explains how to use Big Data Analytics language to create and manage databases. After completing this training course you would be able to use Big Data Analytics on your small database projects. ',
        DESCRIPTION1: 'Training from professional Big Data developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction aux Big Data',
        plan2:'Big Data Modeling and Management Systems',
        plan3:'Big Data Integration and Processing ',
        plan4:'Machine Learning With Big Data',
        plan5:'Graph Analytics for Big Data',
        plan6: 'Big Data - Capstone Project',
        Requirements:'This Big Data Analytics training is designed for Big Data Analytics beginners.',
        count: '5.0 (980)',
        price: '$24.00'
    },
     {
        id: 4,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'NoSQL Training',
        overview: 'This NoSQL course explains how to use NoSQL language to create and manage databases. After completing this training course you would be able to use NoSQL on your small database projects. ',
        DESCRIPTION1: 'Training from professional  NoSQL developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction',
        plan2:'What is NoSQL?',
        plan3:'Different Types of NoSQL Databases ',
        plan4:'Pros and Cons of NoSQL',
        plan5:'Is NoSQL right for your job?',
        plan6: 'Conclusion',
        Requirements:'This NoSQL training is designed for NoSQL beginners. This course is for you if you are interested in learning NoSQL Language practically.',
        count: '5.0 (980)',
        price: '$24.00'
    },
     {
        id: 5,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'GraphQL Training',
        overview: 'This GraphQL course explains how to use GraphQL language to create and manage databases. After completing this training course you would be able to use GraphQL on your small database projects. This course covers a range of GraphQL Concepts. ',
        DESCRIPTION1: 'Training from professional  GraphQL developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction',
        plan2:'Setup and Introduction',
        plan3:'Types and schemas ',
        plan4:'Setting Up persistence',
        plan5:'Mutations',
         plan6:'Queries in Depth',
        plan7: 'Conclusion',
        Requirements:'This GraphQL training is designed for GraphQL beginners. This course is for you if you are interested in learning GraphQL Language practically.',
        count: '5.0 (980)',
        price: '$24.00'
    },
     {
        id: 6,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'SQL for beginners',
        overview: 'This SQL course explains how to use SQL language to create and manage databases. After completing this training course you would be able to use SQL on your small database projects. ',
        DESCRIPTION1: 'Training from professional SQL developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Introduction',
        plan2:'Ask for Data from a Database',
        plan3:'Ask for Data from two or more tables ',
        plan4:'Data types, Math, and Helpful Features',
        plan5:'Add or modify Data',
        plan6: 'Conclusion',
        Requirements:'This SQL training is designed for SQL beginners. This course is for you if you are interested in learning SQL Language practically.',
        count: '5.0 (980)',
        price: '$24.00'
    },
    {
        id: 7,
        classnames: 'course one-of-four text-c100ea MDev',
        imgsrc: 'images/courses/courses-gird-v1-3.jpg',
        title: 'Hadoop',
        overview: 'This Hadoop course explains how to use Hadoop language to create and manage databases. After completing this training course you would be able to use Hadoop on your small database projects ',
        DESCRIPTION1: 'Training from professional Hadoop developers. ',
        DESCRIPTION2:'Real-time Practice and Projects ',
        DESCRIPTION3:'Course Completion Certificate',
        DESCRIPTION4:'Support and Careers Advice',
        plan1:'Hadoop Basics',
        plan2:'Introduction to the Hadoop Stack',
        plan3:'Introduction to Hadoop Distributed File System (HDFS) ',
        plan4:'Introduction to Map/Reduce',
        plan5:'Spark',
        Requirements:'This Hadoop training is designed for Hadoop beginners. This course is for you if you are interested in learning Hadoop Language practically.',
        count: '5.0 (980)',
        price: '$24.00'
    }
]

export default dataTab;
