const dataTab = [
    {
        id: 1,
        classnames: 'course one-of-four text-2ebd59 MDev',
        imgsrc: 'images/courses/iphoneAPP.png',
        title: 'Personal development tools',
        Overview: 'This training allows you to acquire the essential tools that allow you to optimize your professional and interpersonal relationships on a daily basis.',
        DESCRIPTION1: 'Gratitude ',
        DESCRIPTION2:'Happiness ',
        DESCRIPTION3:'Meditation',
        DESCRIPTION4:'Savoring',
        plan1:'Introduction',
        plan2:'Misconceptions About Happiness',
        plan3:'Why Our Expectations are so Bad  ',
        plan4:'How Can We Overcome Our Biases',
        plan5:'Stuff that Really Makes Us Happy',
        plan6:'Putting Strategies into Practice',
        plan7:'Start Your Final Rewirement Challenge ',
        plan8:'Continue Your Rewirement Challenge ',
        Requirements:'An open mind and a willingness to learn.',
        count: '5.0 (980)',
        price: 'FREE'
    },
    {
        id: 2,
        classnames: 'course one-of-four text-ea0042 MDev ',
        imgsrc: 'images/courses/AndroidApp.png',  
        title: 'Communication Skills',
        overview: 'Communication Skills training offers an opportunity to develop self-confidence and know how to work on oneself, to understand the importance of positive communication in establishing and maintaining a relationship of trust with ones interlocutors.',
        DESCRIPTION1: 'Goal setting ',
        DESCRIPTION2:'Communication ',
        DESCRIPTION3:'Negotiation',
        DESCRIPTION4:'Deception',
        plan1:'Cooperation, Competition, and Comparisons',
        plan2:'Trust',
        plan3:'Deception ',
        plan4:'Effective Communication',
        Requirements:'An open mind and a willingness to learn.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 3,
        classnames: 'course one-of-four text-ea0042 MDev ',
        imgsrc: 'images/courses/AndroidApp.png',  
        title: 'Leadership personnel',
        overview:'The Personal Leadership training allows managers and operational managers to get to know themselves better and to know others better in terms of behavior, representations and emotions.', 
        DESCRIPTION1: 'Strategic Thinking ',
        DESCRIPTION2:'Organisational leadership ',
        DESCRIPTION3:'Change planning',
        DESCRIPTION4:'Motivation',
        DESCRIPTION5:'Diversity and Inclusion',
        DESCRIPTION6:'Communication',
        DESCRIPTION7:'Staff Management',
        plan1:'Cooperation, Competition, and Comparisons',
        plan2:'Trust',
        plan3:'Deception ',
        plan4:'Effective Communication',
        Requirements:'An open mind and a willingness to learn.',
        count: '5.0 (980)',
        price: '$49.00'
    },
    {
        id: 4,
        classnames: 'course one-of-four text-ea0042 MDev ',
        imgsrc: 'images/courses/AndroidApp.png',  
        title: 'Public speaking',
        overview:'During this training you will learn to develop charisma, to be able to better manage stress, to be able to structure ones interventions, to have self-confidence and to know how to work on non-verbal communication.',
        DESCRIPTION1: 'Communication ',
        DESCRIPTION2:'Presentation ',
        DESCRIPTION3:'Speech',
        DESCRIPTION4:'Public Speaking',
        DESCRIPTION5:'Confidence',
        plan1:'Introduction to the art of public speaking.',
        plan2:'Speaking to inform: Discussing complex ideas with clear explanations and dynamic slides.',
        plan3:'Speaking to persuade: Motivating audiences with solid arguments and moving language.',
        plan4:'Speaking to Inspire: Ceremonial and Motivational Speeches. ',
        Requirements:'An open mind and a willingness to learn.',
        count: '5.0 (980)',
        price: '$49.00'
    },
]
    export default dataTab;
